version: "3"
services:
  pgdb:
    container_name: postgres_db
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file:
      - config.env
    ports:
      - 5432:5432
    volumes:
      - pg_db_data:/var/lib/postgresql/data

  pgadmin4:
    container_name: postgres_pgadmin4
    image: dpage/pgadmin4:8.9
    restart: always
    depends_on:
      - pgdb
    env_file:
      - config.env
    ports:
      - 5000:80
    volumes:
      - pg_admin_data:/var/lib/pgadmin
volumes:
  pg_db_data:
  pg_admin_data: